spring.application.name=bff-cuidadoseguro

server.port=8090


gateway.url=http://api-gateway-1937747119.us-east-1.elb.amazonaws.com:8080
datosmedicos.url=http://dm-ms-401060910.us-east-1.elb.amazonaws.com:8083

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

spring.main.web-application-type=reactive