spring.application.name=bff-cuidadoseguro

server.port=8090


gateway.url=http://alb-apigateway-706412478.us-east-1.elb.amazonaws.com:8080
datosmedicos.url=http://dmms-305868912.us-east-1.elb.amazonaws.com:8083

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

spring.main.web-application-type=reactive